# Generated by Django 4.0.4 on 2022-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=30)),
                ('course_description', models.CharField(max_length=60)),
                ('course_credits', models.IntegerField()),
                ('course_instructor', models.CharField(max_length=30)),
                ('couse_start_date', models.DateField()),
            ],
        ),
    ]
